project_id = "vmvvvpqwwhybqzxewksd"

[functions.create-stripe-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-munopay-payment]
verify_jwt = true

[functions.munopay-webhook]
verify_jwt = false