// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmvvvpqwwhybqzxewksd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdnZ2cHF3d2h5YnF6eGV3a3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzkwNjUsImV4cCI6MjA3MjcxNTA2NX0.gBDIjjdM_oF2ELd5a8qrXI2eoI501l7li-UuiSvZB94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});